export const primary = '#00807b',
  secondary = '#50E3C2',
  active = '#c4f5f3',
  inactive = '#F8F8F8',
  background = '#ffffff',
  backgroundLight = '#F7F7F7',
  backgroundSecondary = '#FDFBEE',
  text = '#333333',
  border = '#E0E0E0',
  error = '#FF3D00',
  warning = '#FF9800',
  success = '#4CAF50',
  info = '#2196F3',
  lightGray = '#BDBDBD',
  darkGray = '#757575',
  Home = 'Home',
  Insights = 'Insights',
  Reports = 'Reports',
  Profile = 'Profile',
  QR = 'QR',
  CreateGroup = 'CreateGroup',
  Notifications = 'Notifications',
  screens = {
    Home,
    Insights,
    Reports,
    Profile,
    QR,
    CreateGroup,
    Notifications,
  };
